service: app

provider:
    name: aws
    region: ap-southeast-1
    runtime: provided

plugins:
    - ./vendor/bref/bref

functions:
    hello:
        handler: src/index.php
        description: ''
        layers:
            - ${bref:layer.php-80}

# Exclude files from deployment
package:
    exclude:
        - 'tests/**'
